---
name: Update LOLAPPS-Project.github.io
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v2

      - name: Change .yml to .md
        run: |
          for x in $(find yml/ -name '*.yml'); do echo "---" >> "$x"; mv "$x" "${x/%\.yml/.md}"; done
          mv yml/Desktop yml/Desktop_New
          mv yml/Web yml/Web_New
        # mv yml/Mobile yml/Mobile / Commenting out for the time being
      - name: Deploy to LOLAPPS-Project.github.io repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: LOLAPPS-Project/lolapps-project.github.io
          publish_branch: master
          publish_dir: yml
          destination_dir: _lolapps
          enable_jekyll: true
          keep_files: false
          commit_message: "Applying update "
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
